# Web
Web:
  PyWebIO_Enable: true
  Domain: http://127.0.0.1:19080
  PyWebIO_Theme: minty
  Max_Take_URLs: 30
  Tab_Title: Douyin_TikTok_Download_API
  Description: Douyin_TikTok_Download_API local service for server_auto_clip.
  Favicon: https://raw.githubusercontent.com/Evil0ctal/Douyin_TikTok_Download_API/main/logo/logo192.png
  Easter_Egg: false
  Live2D_Enable: false
  Live2D_JS: ""

# API
API:
  Host_IP: 0.0.0.0
  Host_Port: 19080
  Docs_URL: /docs
  Redoc_URL: /redoc
  Version: V4.1.2
  Update_Time: 2025/03/16
  Environment: LocalServer
  Download_Switch: true
  Download_Path: ../../runtime/douyin_downloads
  Download_File_Prefix: server_auto_clip_

# iOS Shortcut
iOS_Shortcut:
  iOS_Shortcut_Version: 7.0
  iOS_Shortcut_Update_Time: 2024/07/05
  iOS_Shortcut_Link: https://www.icloud.com/shortcuts/06f891a026df40cfa967a907feaea632
  iOS_Shortcut_Link_EN: https://www.icloud.com/shortcuts/06f891a026df40cfa967a907feaea632
  iOS_Shortcut_Update_Note: Local deployment config for server_auto_clip.
  iOS_Shortcut_Update_Note_EN: Local deployment config for server_auto_clip.
